"""empty message

Revision ID: 0a78531e76b6
Revises: 021b65fef6aa
Create Date: 2019-02-16 08:40:09.503708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a78531e76b6'
down_revision = '021b65fef6aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('slug_name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location', 'slug_name')
    # ### end Alembic commands ###
